# Generated by Django 2.2.8 on 2020-01-12 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('name', 'email')},
        ),
    ]
